### ISSUE TITLE
[mc6809] Strange code in cpu6809_store_8bit_with_offset()

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#233]
https://github.com/spotlessmind1975/ugbasic/blob/34f7ae6af2dec7b9c4c2dd9136976fa541ec2e53/ugbc/src/hw/6809.c#L4541-L4548

This code loads the offset as a fixed address and not as an immediate (#numeric) value. The value isn't loaded as an immediate value either. That seem very strange.

Isn't this what you rather meant ?
```
     outline1("LDA #$%2.2x", _value); 
     outline2("STA %s+%d, _destination, _offset); 
```

Also: beware that B,X will produce strange result when B>=128 as the addition is actually signed.

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **first of all thanks for the great comments!**

The use of this function is to give the possibility to write within an area addressed by a pointer, as for example in the case of strings. Look at this usage example:

    cpu_dswrite( _environment, result->realName );
    cpu_dsdescriptor( _environment, result->realName, address->realName, size->realName );
    cpu_store_8bit_with_offset(_environment, address->realName, (_x & 0xff), 1 );

We are going to put the byte `_x` on the string indexed by `address` pointer, starting from position 1. 

So actually the error is in these lines:

     outline1("LDB $%2.2x", _offset); 
     outline1("LDA $%2.2x", _value); 

both are missing of `#` symbol. Unfortunately your suggestion cannot work because the string address is dynamic - it is not known at compile time, but only at runtime. The string is not indexed by `%s` but by the content of `%s`, so `B` offset is needed.

> Also: beware that B,X will produce strange result when B>=128 as the addition is actually signed.

Yes, this is a problem I was aware of. Let's say that, at the moment and if we don't come up with something brilliant, on 6809-based platforms, strings can be a maximum of 128 characters long. I think that's too much of a limitation, so I'll work on it.

**Comment by spotlessmind1975** [comment]
Fixed.

**Comment by Samuel-DEVULDER** [comment]
> > Also: beware that B,X will produce strange result when B>=128 as the addition is actually signed.
> 
> Yes, this is a problem I was aware of. Let's say that, at the moment and if we don't come up with something brilliant, on 6809-based platforms, strings can be a maximum of 128 characters long. I think that's too much of a limitation, so I'll work on it.

There is the work around using "ABX", it adds B to X in an unsigned way in a very compact and fast way (1byte, 3cycles). And after you even got B free for whatever you want. 

I also noticed you didn't use the ",REG+" or ",-REG" very much in string handling. This  addressing mode is kind of special to the mc6809 and will be largely used later on its 16 and 32bit successors (mc680x0). Using those mc6809 addressing modes, cpu6809_flip() become shorter and doesn't suffer the 128bytes limitation of B,X:
```
        outline1("LDU %s", _source); // I use U instead of Y because LDU/STU are both shorter and faster
        outline1("LDX %s", _destination);
        outline1("LDB %s", _size);   // What happen if size=0 ? May bad add  outline1("BEQ %sdone", label);  after LDB
        outline0("ABX");
        outhead1("%sx", label);
        outline0("LDA ,U+"); // or PULU A
        outline0("STA ,-X"); // >>,-X<< mean X is decremented by 1 byte before we write to the memory, just like *--x = val in C :)
        outline0("DECB");
        outline1("BNE %sx", label);
        outhead1("%sdone", label);
```
to be compared with:
https://github.com/spotlessmind1975/ugbasic/blob/34f7ae6af2dec7b9c4c2dd9136976fa541ec2e53/ugbc/src/hw/6809.c#L4154-L4169

**Comment by spotlessmind1975** [comment]
> There is the work around using "ABX", it adds B to X in an unsigned way in a very compact and fast way (1byte, 3cycles). And after you even got B free for whatever you want.

@Samuel-DEVULDER **this is a fantastic suggestion!**

I will implement it as soon as possible, it would be great to go over that limit.
