### ISSUE TITLE
add_complex() unsigned ?

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#250]
This is something I identified with the starfield when the "cross-hair" (the white point actually) goes past the left or top border of the screen. By using something like `ADD x0,dx, min TO max` I presumed that when x0<min then it wraps back to max, but this is not what I observe when min=0: x0 keeps getting negative.

I can track down this issue to this like:
https://github.com/spotlessmind1975/ugbasic/blob/33ff7da9540337141c8a328836026a2366e36af1/ugbc/src/targets/common/add.c#L95

Look at the final parameter: 0. The x0<min is done in an unsigned way while both x0 and min  signed (I presume as I don't know how to declare an unsigned variable or constant). 

Is this a bug or a feature ?

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER , I'm afraid I don't understand the problem very well. I assume that the bitwidth of all terms in play is the same. The final parameter indicates whether equality must be considered in the comparison (`1`) or not (`0`). If the sign agrees, the comparison is made signed or unsigned, based on sign of the variables.

So let's recap.

     VAR a AS SIGNED WORD = 0
     ADD a,-1,0 to 100 : ' now a = 100

This is how it should work, and how it works under Commodore 64.

Are you experiencing something different?

**Comment by Samuel-DEVULDER** [comment]
I wasn't clear enough. See the source. Variable x0 is declared by simple assignment from SCREEN WIDTH/2 line 39. 
https://github.com/Samuel-DEVULDER/ugbasic/blob/b1e2dee1be992c39c0331286dd509e8b3ca75de3/examples/contrib_starfield.bas#L39

> The final parameter indicates whether equality must be considered 

Ooops I was confused with cpu_less_than() whose last param mean unsigned.

Does that mean x0 was actually implicitly declared as an unsigned value ? 
I assumed it was just a 16bit integer like when I initialize it with x0=160.

Why is it an unsigned value this time ?

**Comment by spotlessmind1975** [comment]
> Does that mean x0 was actually implicitly declared as an unsigned value ?

In the source, `x0` is defined as:

      x0 = (SCREEN WIDTH / 2)

 * `SCREEN WIDTH` returns a `POSITION` value, that is a `SIGNED WORD`. 
 * Also `2` is internally converted into a `WORD`. 
 * Since signs discord, and the first is signed, the second is converter to `SIGNED WORD`.
 * When the division is done, the result and the remainder are stored as WORD.
 * **This last step is the bug!**

**Comment by Samuel-DEVULDER** [comment]
There is something else. Consider this:
```
a = 4 : dx = 0 : DEC dx
ADD a,dx,0 TO 10 : PRINT a
ADD a,dx,0 TO 10 : PRINT a
ADD a,dx,0 TO 10 : PRINT a
ADD a,dx,0 TO 10 : PRINT a
ADD a,dx,0 TO 10 : PRINT a
ADD a,dx,0 TO 10 : PRINT a
HALT
```
It prints
```
3
2
1
0
0
0
```
e.g. it doesn't wrap back to 10. 

Is it a bug or something I don't understand correctly ?

**Comment by spotlessmind1975** [comment]
> Is it a bug or something I don't understand correctly ?

On ugBASIC, implicit numeric variables are defined as unsigned (`WORD`). So your example just adds `65535` to the value of the given variable. Because of the overflow, this is equivalent to subtracting `1`. However, when you arrive to `0`, the result is not `-1` but `65535`. At this point, the check on the upper limit verifies that the variable is greater than `10` and therefore the variable is given the value `0`. This last step is repeated indefinitely, and therefore remains stationary at `0`.

Try this version:

    DEFINE DEFAULT TYPE SIGNED WORD
    a = 4 : dx = 0 : DEC dx
    ADD a,dx,0 TO 10 : PRINT a
    ADD a,dx,0 TO 10 : PRINT a
    ADD a,dx,0 TO 10 : PRINT a
    ADD a,dx,0 TO 10 : PRINT a
    ADD a,dx,0 TO 10 : PRINT a
    ADD a,dx,0 TO 10 : PRINT a

In this case, having all the variables the sign, there is no overflow but pure mathematics in 2's complement.

**Comment by spotlessmind1975** [comment]
Fixed: @Samuel-DEVULDER can you check if it works? Thank you!

**Comment by Samuel-DEVULDER** [comment]
okay I understand. This is because numerical constants are unsigned. Actually I am used to basic with only signed integers, so I suppose `DEFINE DEFAULT TYPE SIGNED WORD` should be my first line in sources :)

**Comment by spotlessmind1975** [comment]
Fixed.
