### ISSUE TITLE
Lots of (unnecessary) calls to DSFREE

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#256]
If you compile [this code](https://github.com/Samuel-DEVULDER/ugbasic/blob/6809opt/examples/contrib_starfield.bas) and have a look at the ASM you'll see lots of consecutive calls to DSFREE with the same parameter. These appear even in lines of code not even using strings. For instance, just before computation of (x OR y) in [line 61](https://github.com/Samuel-DEVULDER/ugbasic/blob/d955ad150edc5f5e43210dc3b50672f50d764eb2/examples/contrib_starfield.bas#L59-L61) where no string are used, the ASM has 2 calls to DSFREE on _Tmp108:
```
	STD _y
	LDB _Ttmp108  <===
	JSR DSFREE    <===
	LDB _Ttmp108  <===
	JSR DSFREE    <===
	LDD _x
	ORA _y
	ORB _y+1
	STD _Ttmp127
```
There can be more than 2, or 3 calls in a raw. For instance, later in the ASM one ca find 4 calls in a raw:
```
	STD _irnd
_label155e
	LDB _Ttmp108
	JSR DSFREE
	LDB _Ttmp108
	JSR DSFREE
	LDB _Ttmp108
	JSR DSFREE
	LDB _Ttmp108
	JSR DSFREE
	LDD _x0
	ANDCC #$FE
	EORA #$FF
	EORB #$FF
	ADDD #1
	LDY _x
	LEAY D, Y
	STY _Ttmp127
```
Sometimes labels are interleaved as for example just before the declaration of the variables by the end of the file:
```
_label211e
	LDB _Ttmp108
	JSR DSFREE
_label196f
_label196e0
	LDB _Ttmp108
	JSR DSFREE
	JMP _label100
_label100bis
	LDB _Ttmp108
	JSR DSFREE
	LDB _Ttmp108
	JSR DSFREE
_label218
	JMP _label218
_PEN rzb 1
_PAPER rzb 1
_windowE rzb 1
_windowS rzb 1
```

This is very odd. Needless to say this slows down the execution and increase memory footprint.

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER , **thank you for your analisys.**

So, I'm not entirely sure if this is a bug, I classified it as a code review issue. I have reason to believe that the code is generated from the code in `_infrastructure.c: 125-127` (referred to commit c40cc27 ). This code is executed at the end of each line of code (statement), to reset the temporary variables so that they can be reused with the next line of code (statement).

On line `contrib_starfield.bas: 50` a variable of type "dynamic string" is instantiated, and it is the argument of the `PRINT`, and from that moment on, we make sure that the reference to the string has been deallocated, to avoid "strings hanging".

The fix was to deallocate the string only and only if the variable was used in the previous expression. In doing so, the calls have been drastically reduced.

**Comment by Samuel-DEVULDER** [comment]
Marvelous ! 

For information, after that "fix", the [starfield](https://github.com/Samuel-DEVULDER/ugbasic/blob/6809opt/examples/contrib_starfield.bas) raised from ~15fps up to ~20fps (+30% speedup) with the various optims on my [6809opt branch](https://github.com/Samuel-DEVULDER/ugbasic/tree/6809opt). This is pretty good for this old 6809 :) 

If you wan't to compare the generated profile between the "main" branch and the "6809opt", here is a ZIP with the various files.
[ugbasic.zip](https://github.com/spotlessmind1975/ugbasic/files/7605521/ugbasic.zip)

**Comment by spotlessmind1975** [comment]
**Wow, that's a fantastic result!**

When do you think he'll be ready for a nice merge?

**Comment by Samuel-DEVULDER** [comment]
I have a few couples of optims in my sleeves:
* move temporary to code (inline variable), 
* detect temporaries that are not read (yes there are a few, mainly because only the 16bits lower part of 16x16 mul is used).
I think that after this a merge can be done.

Notes:
* if you look at the asm, the optimizer removes some temporaries by presuming they are dead. This presumption is very crude (but can be disabled), and I'd like to make it more smart. A good thing would be that the upper-level API notifies the "cpu_xxx" level that some temporary is dead so that the optimizer can make good use of this info. Well this is a major thing that I'll do later.
* I'll surely hand-optimize some other */6809/*.asm files later as well (I've done those really important for the starfield).

Oh, and I've just spotted something funny with `DIM ctab AS BYTE (nums+1)`. The generated code makes a multiplication by 1 ! Maybe CPUMATHMUL16BITTO32BIT  can detect this case and return quickly, or better optimize the generator to detect this case and a higher level and avoid the multiplication. This will  improve code for all cpus.

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER , I can't wait to see your work merged with the main ugBASIC branch: I think it will add great value, which Thomson computer users will appreciate!

I only have a question, with respect to the optimizations you carry out, so as to understand if I understand correctly.

> if you look at the asm, the optimizer removes some temporaries by presuming they are dead. This presumption is very crude (but can be disabled), and I'd like to make it more smart. A good thing would be that the upper-level API notifies the "cpu_xxx" level that some temporary is dead so that the optimizer can make good use of this info. Well this is a major thing that I'll do later.

What do you mean by "temporary is dead"? As things stand, all temporary variables are reused, so they are never really "dead". But perhaps I have not understood well the entire question (which is likely since you are optimizing so good!)

**Comment by Samuel-DEVULDER** [comment]
A temporary is dead if it is written twice without bein read in between. The first write can safely be removed. This is the kind of info I used in the past for my [680x0 Peephole-optimizer](https://github.com/Samuel-DEVULDER/popt) that I released long ago for the Amiga.
