### ISSUE TITLE
Buggy multiplication ?

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#274]
While testing examples/maths_example_02.bas, where I got wrong result I came along this one-line code:
`PRINT 3*3*3`
It prints 0 on the MO5/PC128op, and may be on other platforms. Of course this isn't the expected result.

Looking at the ASM I found out this:
```
33C6  BE57D9                  LDX _Ttmp0
33C9  9F14                    STX <MATHPTR0
33CB  BE57DB                  LDX _Ttmp1
33CE  9F16                    STX <MATHPTR2
33D0  BD3323                  JSR CPUMATHMUL16BITTO32BIT
33D3  9E18                    LDX <MATHPTR4
33D5  BF57DD                  STX _Ttmp2
33D8  9E1A                    LDX <MATHPTR6
33DA  BF57DF                  STX _Ttmp2+2
```
Ok this computes the first 3*3. Result is stored in _Ttmp2(<==upper word==0) and _Ttmp2+2(<==lower word==9)
```
33DD  CC0003                  LDD #$0003
33E0  FD57E1                  STD _Ttmp3
33E3  7F57E3                  CLR _Ttmp4
33E6  7F57E4                  CLR _Ttmp4+1
33E9  FC57E1                  LDD _Ttmp3
33EC  FD57E5                  STD _Ttmp4+2
```
this is allocation of tmp4 = ($0000,$0003) for second multiplication.. But look at his:
```
33EF  BE57DD                  LDX _Ttmp2   ; upper word of previous result == 0
33F2  9F14                    STX <MATHPTR0
33F4  BE57E3                  LDX _Ttmp4 ; upper word of tmp4 == 0
33F7  9F16                    STX <MATHPTR2
33F9  BD3323                  JSR CPUMATHMUL16BITTO32BIT
```
Here is the issue: the second multiplication takes the upper word of both arguments instead of lower word. This result in 0 which cancel any further multiplication.

This mean that any expression containing multiplication with a 32bit temporary will produce 0.

**Comment by Samuel-DEVULDER** [comment]
Hmm examples/maths_example_05.bas seem buggy as well since
` PRINT "1 + (8 * -1) = ";1 + (8 * -1)`
prints 0.

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER **thank you for your kind bug report!**

> While testing examples/maths_example_02.bas, where I got wrong result I came along this one-line code:

In the example you cite the executed code is:

       b = 3*3*3*3*3
       PRINT "3*3*3*3*3 = ";b

On the Commodore 64 it returns `243`, while on the Dragon 32 it returns `0`. So it would seem related to a multiplication problem on the Motorola 6809 processor.

> This mean that any expression containing multiplication with a 32bit temporary will produce 0.

Ahhhh, ok, so it's clear that the problem is the 32-bit multiplication routine, due to the "type change" during multiplication (16 bit -> 32 bit -> ...), which was induced by one of the fixes we made. I should have known. So ok, I need to implement 32-bit multiplication with 32-bit result, I have no choice. 

**I work on it and I'll fix it.**

**Comment by Samuel-DEVULDER** [comment]
> On the Commodore 64 it returns `243`, while on the Dragon 32 it returns `0`. So it would seem related to a multiplication problem on the Motorola 6809 processor.

Isn't this simply related to word-order ? We should take values at <memory>+2 when calling 16x16 mul on 32bits values for the  6809-based 32bits mul, don't we?

**Comment by spotlessmind1975** [comment]
Yes, it could be, thanks for the tip!

At the moment I have not yet looked into the sources, I have only seen the symptom. I wanted to make sure it was a problem that had escaped my various internal tests rather than a structural problem.

Anyway, every suggestion is welcome!
So if you have an idea I gladly explore it as soon as possible.

**Comment by spotlessmind1975** [comment]
Fixed (the @Samuel-DEVULDER suggestion was correct, **thank you!)**
