### ISSUE TITLE
[MO5/PC128op] Invalid counter size/decrement in compilation of "ON EVERY N"

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#277]
While debugging examples/control_periodic_01.bas for the Thomson's, I found out two issues:
* one in the asm (DP is not properly reset to the direct page before calling the hook, and we should use a JMP ,X instead of a JSR). I can fix these on my misc_thomson_changes branch and provide a separated PR for these. [EDIT][done](https://github.com/spotlessmind1975/ugbasic/pull/278)
* the other one requires a more knowledge of the basic and might be present on all the platforms, so I simply report it:
The "every counter" is declared as a word:
https://github.com/spotlessmind1975/ugbasic/blob/26452880b018ef52c2182f094714dcbb3ff39f4a/ugbc/src/targets/pc128op/every_gosub.c#L62
But later it is decremented as a byte:
https://github.com/spotlessmind1975/ugbasic/blob/26452880b018ef52c2182f094714dcbb3ff39f4a/ugbc/src/targets/pc128op/every_gosub.c#L79

This works seemingly fine on low-endian machines, but on 6809 this mean we only decrement the high byte, resulting in a period of 256 interrupts regardless of the integer provided to the "ON EVERY" instruction.

So there is a mismatch there in the code that is possibly present on all machines.

The question is:
* Shall the counter be declared as byte and `cpu_dec()` is to be used, or
*  shall it be kept as word, and `cpu_dec_16bit()` be used ?

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER, and **thank you for your analisys!**

First of all, I confirm that I have merged your changes. So if all goes well, the fix will come out with the next scheduled version.

To answer your question, it was not a problem that I have posed myself (indeed, it could be a bug in all respects).

The semantics of `EVERY` is to use `TICK`s (1 / vertical refresh rate) as the unit of measurement of the time to wait. If we use only one byte we get a more optimized code but at most a period of about 1.5 seconds (NTSC) or about 2.5 seconds (PAL). Using a word we have that the routine will be called at most every 546 seconds (NTSC) or 655 seconds (PAL).

Here it should be understood if EVERY is a "raster" instruction (and then 1 byte is more than enough, otherwise a polling is to be preferred) or if it is a "pending" instruction, and then a word is more suitable. The first solution seems more logical to me, but first I would like to hear your opinion.

**Comment by Samuel-DEVULDER** [comment]
> The semantics of `EVERY` is to use `TICK`s (1 / vertical refresh rate) as the unit of measurement of the time to wait. If we use only one byte we get a more optimized code but at most a period of about 1.5 seconds (NTSC) or about 2.5 seconds (PAL). Using a word we have that the routine will be called at most every 546 seconds (NTSC) or 655 seconds (PAL).

First, I don't quite understand the calculus. A byte can hold 256 values, on a 60hz tick, this makes a max period of 255/60 = ~4.27 seconds for NTSC and 255/51 = 5.1 sec for seconds for PAL.

Then, why not let the user decide himself the "size" of the counter by using the size of the provided value (possibly a casted value in case of constant). Hence `ON EVERY (BYTE)50` would use a byte counter, whereas `sec=50 : ON EVERY sec` will use a WORD counter since `sec` is a word. And for the completion `day = 50*3600*24 : ON EVERY day` should use a 32 bit value since `day` is then a 32 bit value (I doubt someone will use this, but why limiting?)

**Comment by spotlessmind1975** [comment]
> First, I don't quite understand the calculus. 

Sorry, I wrongly wrote the NTSC time. Anyway, your times are for CPU 6502 and Z80, that have unsigned bytes. Using signed bytes it takes at most 127 as value, so 127/60 = ~2 seconds for NTSC and 127/50 = ~2,5 seconds for PAL. In this case, it is necessary to consider an intersection between the two types, to be isomorphic.

> why not let the user decide himself the "size" of the counter by using the size of the provided value (possibly a cast value in case of a constant). 

It sounds like a very interesting idea. 
Especially since the choice of type is at compile time.

> we could move every_gosub.c from src/target/<cpu> to src/target/common/ as all the interrupts code share lots of common structure.

I would say that for this it is necessary to open a dedicated issue  ( #281 ).

**Comment by spotlessmind1975** [comment]
Fixed.
