### ISSUE TITLE
[6809] printing 1 + (8*-1) or $FFF9 displays 0

### ISSUE THREAD

**Issue by Samuel-DEVULDER** [spotlessmind1975/ugbasic#283]
https://github.com/spotlessmind1975/ugbasic/blob/d51eab2e10a251eb7a938e9495e1e771424fa3d3/examples/maths_example_05.bas#L11

This example prints 0.

The asm looks okay for the calculation ($fff9 = -7 is computed), but the print routine is asked to print $FFF9 as unsigned, unfortunately, N2STRING will print 0 for $FFF9 because after any subtraction of 10000, 1000, 100, 10 and 1, the result will always have its sign-bit set, so the print routine believe there is 0 times 10000, then 0 times 1000, etc. Well 0 everywhere.
https://github.com/spotlessmind1975/ugbasic/blob/d53b8869ef665152bd2812d84fe4205778e609bd/ugbc/src/hw/6809/number_to_string.asm#L57-L63

I think the number2string shall be reworked. If you want I can try to do it, and make it also print 32bits integers as the present implementation doesn't support it. I have a handy routine with DAA (digital adjustment) that will work fine for any number size IIRC.

The other weird stuff is in the computation of absolute values is wrong:
https://github.com/spotlessmind1975/ugbasic/blob/d53b8869ef665152bd2812d84fe4205778e609bd/ugbc/src/hw/6809.c#L4379-L4385
There is no carry propagation from LSB to MSB int hat code!

This is a point where 6502 and 6809 differ: addition/subtraction with carry/borrow (ADCA/SBCA) is a different opcode than simple addition/subtraction (ADDA/SUBA). This also explain why we don't need to preset the carry prior to do addition/subtraction on the 6809.

I can also handle this point if you want.

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER, **thanks for proposing!**

> I think the number2string shall be reworked. 

You are definitely right! 
It was a routine nightmare for me.
I am not at all surprised that you suggest to rework it.
I'm also happy if you can extend it to 32 bits!

> The other weird stuff is in the computation of absolute values is wrong:
> I can also handle this point if you want.

Feel free to tackle this feature as you see it fit. As you may have guessed, where I do not arrive with the expertise on the 6809, I take full hands from the 6502. Inspiration is not always right! On the other hand, I am happy with the review of the code by those who have more experience, because in the end all users gain in quality.

So ... thank you again and go ahead! 👍

**Comment by spotlessmind1975** [comment]
Fixed.
