### ISSUE TITLE
compilation is unbuntu 20.04

### ISSUE THREAD

**Issue by fabiodl** [spotlessmind1975/ugbasic#350]
running make gives
``bison: invalid argument ‘counterexamples’ for ‘--warning’

commenting out the` -Wcounterexamples` option lets compilation proceed, but it halts at
``*** No rule to make target 'src-generated/modules_.c', needed by 'objs./src/hw/d32.o'.  Stop.

**Comment by spotlessmind1975** [comment]
**hello @fabiodl , and thank you for reporting the anomaly.**

Currently the reference release for compiling the linux version is Ubuntu 20.10, so this may be the problem. In any case, let's see if we can find a solution for each of the error messages.

      ``bison: invalid argument ‘counterexamples’ for ‘--warning’

This error message depends on the version of BISON installed. The standard version does not include that option, which instead is available in the **bison (GNU Bison) 3.7 version**. In any case, this is not, in my opinion, a blocking problem because the option can be omitted (it is only necessary in development).

     ``*** No rule to make target 'src-generated/modules_.c', needed by 'objs./src/hw/d32.o'. Stop.

This error indicates that the `target` for which you want to generate the compiler has not been given. The ugBASIC compiler provides an independent executable for each retrocomputer. The current list of available targets are [listed here](https://retroprogramming.iwashere.eu/ugbasic:targets), inside the parentesys. A short list is here:

   * `atari` - Atari 400/800
   * `atarixl` - Atari XL/XE
   * `c64` - Commodore 64
   * `plus4` - Commodore PLUS/4
   * `vic20` - Commodore VIC-20 (expanded)
   * `d32` - Dragon 32
   * `d64` - Dragon 64/200-E
   * `pc128op` - Olivetti PC128 Prodest
   * `mo5` - Thomson MO5 
   * `coleco` - ColecoVision
   * `msx1` - MSX
   * `sc3000` - SEGA SC-3000
   * `sg1000` - SEGA SG-1000
   * `zx` - ZX Spectrum 48K

Once the target has been decided, the compiler can be generated with the following command (this is valid for Commodore 64):

    make target=c64 clean compiler

The compiler will be available on `ugbc/exe/ugbc.c64`.

If you want to compile the examples too, you must also indicate the format in which the executables are to be generated, and this depends on the target, as follows:

   * `atari` - output = `xex`
   * `atarixl` - output = `xex`
   * `c64` - output = `prg`
   * `plus4` - output = `prg`
   * `vic20` - output = `prg`
   * `d32` - output = `bin`
   * `d64` - output = `bin`
   * `pc128op` - output = `k7`
   * `mo5` - output = `k7`
   * `coleco` - output = `rom`
   * `msx1` - output = `rom`
   * `sc3000` - output = `rom`
   * `sg1000` - output = `rom`
   * `zx` - output = `tap`

Once the target and output format have been decided, the examples can be generated with the following command (this is valid for Commodore 64):

    make target=c64 output=prg clean all

The examples will be also available on `generated/c64/exe`.

**Comment by fabiodl** [comment]
Thank you for your detailed explanation, I built it with no problems, I was missing the target= part!
