### ISSUE TITLE
[PC128][DBL BUFFER] PUT IMAGE WITH TRANSPARENCY not working

### ISSUE THREAD

**Issue by cttpla** [spotlessmind1975/ugbasic#368]
On PC128, this code doesn't show the black color as transparent from the loaded picture (any picture with 0,0,0 as black is good).
Instead, it doesn't show any pixel of it. Omitting WITH TRANSPARENCY shows the image including black pixels.

    SCREEN #3
    BITMAP ENABLE (160,200,16)
    'Palette
    PALETTE RGB(0,0,0),RGB(255,0,0),RGB(255,255,0),RGB(255,255,0), _
    		RGB(0,0,255),RGB(255,0,255),RGB(0,255,255),RGB(255,255,255), _
    		RGB(187,187,187),RGB(221,119,119),RGB(119,221,119)
    '
    tile1 := LOAD IMAGE("...")
    ' 
    DOUBLE BUFFER ON
    '
    CLS RED
    '
    DO
    PUT IMAGE tile1 AT 80, 100 WITH TRANSPARENCY
    SCREEN SWAP
    LOOP

**Comment by spotlessmind1975** [comment]
**Hello @cttpla and thank you for signaling the anomaly!**

It is probably a problem related to the fact that any documentation about this feature is missing (I will improve it). In order to have the support for transparency, the images must be loaded using `TRANSPARENCY` keyword at the end.

i.e.

    tile1 := LOAD IMAGE ("...") TRANSPARENCY

Moreover, if an image must be overlayed by another, it should be loaded with the `OVERLAYED `keyword.

    background := LOAD IMAGE ("...") OVERLAYED

Please, repeat the test with these modifications and reopen the ticket if the problem persists.

Thank you again!
