### ISSUE TITLE
Peephole optimizer 6809: format not a string literal and no format arguments

### ISSUE THREAD

**Issue by spotlessmind1975** [spotlessmind1975/ugbasic#422]
The compilation of the current source presents the following warning for targets with Motorola 6809 processor and active optimization:

      src/targets/d32/_optimizer.c: In function ‘vars_remove’:
      src/targets/d32/_optimizer.c:1228:13: warning: format not a string literal and no format arguments [-Wformat-security]
       1228 |             optim(buf[0], "unread",rep);
            |             ^~~~~

I think this is a false warning: anyway, I ask if @Samuel-DEVULDER could be kind enough to check, and possibly give me a suggestion to solve the issue. Thank you!

**Comment by Samuel-DEVULDER** [comment]
This is caused by the printf attribute defined here:
https://github.com/spotlessmind1975/ugbasic/blob/5cb80b397a575f4e5ce03c7ad153200bfbebe14e/ugbc/src/targets/d32/_optimizer.c#L433-L436

Because of this, Gcc expect the third argument (rep) to be a string literal like the first argument of printf() which isn't the case. 
https://github.com/spotlessmind1975/ugbasic/blob/5cb80b397a575f4e5ce03c7ad153200bfbebe14e/ugbc/src/targets/d32/_optimizer.c#L1228
I think using `optim(buf[0], "unread", "%s", rep);` instead will produce the same result, but avoid the warning.

**Comment by spotlessmind1975** [comment]
**Hello @Samuel-DEVULDER , first of all thank you for your suggestion!**

Unfortunately, the code replacement did not bring benefits. This is because the string "(null)" is generated and, therefore, the compilation stops. I will try, in the next few days, to study your workaround better, because in my opinion it is correct and therefore there is only something that escapes me.

**Comment by Samuel-DEVULDER** [comment]
You are right, this is caused by the initialization of rep as NULL
https://github.com/spotlessmind1975/ugbasic/blob/5cb80b397a575f4e5ce03c7ad153200bfbebe14e/ugbc/src/targets/d32/_optimizer.c#L1218
I think initializing it as an empty string "" fixes it.

I now have access to a PC and can try to see if this works. I just need to know on which example/ file I can test this.

**Comment by spotlessmind1975** [comment]
Fixed.
