### ISSUE TITLE
Ellipse has a weird behavior at its limit

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#531]
I have typed the following code 
```
BITMAP ENABLE (160,200,16)
CLS
ELLIPSE 80,100,0,1

```
And i expected to see nothing displayed, instead I got that : 
![image](https://user-images.githubusercontent.com/118670680/206008307-17979b85-a259-4568-8cfc-1d863b3fb3d4.png)

It is the same result if i write ELLIPSE 80,100,1,0 but if I write
ELLIPSE 80,100,0,0 I got : 
![image](https://user-images.githubusercontent.com/118670680/206009355-30a11b5d-4d8e-41ba-acd5-f0ad5c503ff4.png)

I really think that the cosmetic part, isn't a problem, but after this line if I draw a second correct ellipse, I see nothing to I think it is a real bug.

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector and **thank you for your bug report!**

I think that you pointed out a limitation in the implementation of the ellipse. It certainly depends on the way in which the points are calculated and on the fact that, by not using floating point numbers, the representation can diverge with very small steps (as happens in this case). 

So, I agree with you that I don't think there is much room for improvement other than controlling input parameters -- which is never done for other features due to the effect of having bad performance.
