### ISSUE TITLE
EVERY x TICKS GOSUB doesn't work on CPC

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#535]
I wanted to use the EVERY x TICKS GOSUB to manage a small game with a scrolling and an interactive object.
I wanted to call every x TICKS some code to do the scroll and every y TICKS some other code to check if the joystick is triggered to move the object.
It was intented to avoid checking the joystick too often and allow a smooth scrolling (or at least as smooth as it can be on a CPC without doing assembly tricks).

But it didn't work, so I typed this code adapted from the documentation to illustrate the bug : 
```
BITMAP ENABLE
'Palette
DIM myPalette(16) = #{RGB(255,0,0),RGB(255,0,128),RGB(255,0,255),RGB(255,128,255), _
      RGB(255,128,128),RGB(255,128,0),RGB(255,255,0),RGB(255,255,128), _
      RGB(255,255,255),RGB(128,255,255),RGB(0,255,255),RGB(0,128,255), _
      RGB(0,128,128),RGB(0,0,255),RGB(0,0,128),RGB(0,0,0)}

 PALETTE myPalette(0),myPalette(1),myPalette(2),myPalette(3), _
      myPalette(4),myPalette(5),myPalette(6),myPalette(7), _
      myPalette(8),myPalette(9),myPalette(10),myPalette(11), _
      myPalette(12),myPalette(13),myPalette(14),myPalette(15)
colorIndex = 0
CLS

COLOR BORDER  myPalette(0)
EVERY 50 TICKS GOSUB changeBorderColor

EVERY ON

HALT

changeBorderColor:
   COLOR BORDER myPalette(colorIndex)
   colorIndex = colorIndex + 1
   IF colorIndex > 16 THEN
      colorIndex = 0
   ENDIF
   EVERY ON
   RETURN

```

The line COLOR BORDER  myPalette(0) is there to show that this instruction is working so the border turns to red (also the paper but that's because it's color #0). But after that, changeBorderColor is never called, the screen remains all red !
I tested it on CPC and also on MSX where I only got a black screen but I don't know much about MSX so I'm not sure it's relevant.

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank you for bug reporting!**

I fixed the problem only on CPC, which depended on a non-implementation. You can download the COLDFIX v1.12 [rev. 20221213.0038] with which you get a flashing screen. On MSX (and other platforms) it is yet to be implemented.

However, I advise against using the approach of installing two periodically called routines, because currently only one routine can be installed (either called `EVERY...GOSUB` or `EVERY...CALL`). Installing more routines requires extending the instruction, which is a task I've already tracked on github ( #536 ).

Another problem is that scrolling takes a relative long time to execute, and therefore exceeds the time of a tick. This implies that if you mix peripheral input and scrolling, peripheral input will be penalized. It might be better to move the input detection to the timed routine, leaving the scrolling to the main program. The scrolling speed should thus be constant -- whatever it is.
