### ISSUE TITLE
Problem with Instruction BAR

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#554]
I used BAR in the past for a simple program : 
```
BITMAP ENABLE (160,200,16)
CLS
BAR 10,10 TO 30,30,RGB(0, 128, 0)
BAR TO 50,10,RGB(255, 255, 255)
BAR TO 70,10,RGB(255, 0, 0)
```
It worked well in the past but now the italian flag is incomplete ! 
è uno scandalo ! ;)
![image](https://user-images.githubusercontent.com/118670680/212983776-19fbd179-04b2-4ca6-b345-18e1d08f38b2.png)

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector and **thank your for bug reporting!**

Non è uno scandalo! :)

The program does not seem correct, or rather it is right that the Italian flag is not drawn. In fact, the first statement draws a rectangle from (10,10) to (30,30). The second statement, however, draws from (30, 30) to (50,10). Finally, the third draws from (50,10) to (70,10). Since the ordinate of the second and third instruction is the same, it draws a single line.
