### ISSUE TITLE
Bad command using RESOLUTION and ORIGIN

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#563]
I have typed and tested this program and added the RESOLUTION and ORIGIN instruction after to adapt it.
```
BITMAP ENABLE (160,200,16)
CLS
RESOLUTION 640,400
ORIGIN 0,400 UP
COLOR BORDER RGB(0,0,0)
PAPER RGB(0,128,0)	
PEN RGB(0,255,0)
fullscreen$=STRING(CHR$(190), 120)
FOR i=4 TO 20 STEP 6
LOCATE 0,i:PRINT fullscreen$
NEXT

PEN RGB(0,128,255)
BAR 0,0 TO 160,50

FOR i=0 TO 30
	POLYLINE 0,50+i TO 30,30+i TO 60,50+i TO 80,50+i TO 120,20+i TO 130,30+i TO 150,50+i TO 160,50+i
NEXT	

HALT

```
When I launch it on Amstrad CPC after a long load, the Amstrad says Bad Command.
It fails to launch also on MSX with another behaviour.

If I remove the RESOLUTION and the ORIGIN line, the program runs on both machine (even if it's not what I expected on MSX, but it must come from my program).
If I only remove RESOLUTION, the program runs, with a result, but if I remove ORIGIN and keep RESOLUTION, the program just hangs doing nothing.
Here are my compiler options : 
![image](https://user-images.githubusercontent.com/118670680/218313555-4ce1cac8-357e-451d-8144-9a499f9920e9.png)

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector, and **thank you so much for the bug report!**

The real problem, in this case, was in the POLYLINE statement. Or rather, in the assembly code that was directly generated for each point. In practice there was an amplification of assembly code that saturate the available memory on z80 platforms. I solved it by transforming the line drawing primitive into a real function, which is then called when necessary. This greatly reduced the size of the executable so it could be compiled, and run.

However, the syntax of the POLYLINE instruction hides a pitfall: in fact, the previous implementation for calculating the geometric transform according to the resolution and origin of the graphics forced me to continuously switch from the screen reference system to the virtual one. However, the syntax of this command is the only one that allows "chaining" of calculations -- and this creates a problem, because the calculation follows syntactic analysis and not semantics. In other words, the way the source is parsed results in an order of calls for which the computation of the coordinates was done twice. In fact, invalidating the whole thing.

I fixed it by refactoring the transform technique and, at the same time, verifying that it worked on various platforms -- and this allowed me to notice a (tiny but annoying) bug in the 32-bit division calculation procedure on 6502 processors, which I corrected.

Finallty, I got this:

![image](https://user-images.githubusercontent.com/11718606/218338272-0e7c717e-7c13-473b-923f-9047d6cb233e.png)

Fixed with COLDFIX v1.13 [rev. 20230212.2202].
