### ISSUE TITLE
ugbasic/ugbc' src/targets/coco/_optimizer.c error during compile

### ISSUE THREAD

**Issue by mrgw454** [spotlessmind1975/ugbasic#565]
Hello.  Trying to compile the the latest ugBasic source from git (for the CoCo target) on a 64bit Windows 10 system using MinGW.  (Latest official release of ugBasic doesn't have the '-O bin' option yet).  In any case, getting an error when trying to compile using the following command:

``
# make target=coco compiler
make[1]: Entering directory '/home/Ron/source/ugbasic/ugbc'
src/targets/coco/_optimizer.c:1:1: error: expected identifier or '(' before '.' token
    1 | ../d32/_optimizer.c
      | ^
make[1]: *** [makefile:512: objs.coco/src/targets/coco/_optimizer.o] Error 1
make[1]: Leaving directory '/home/Ron/source/ugbasic/ugbc'
make: *** [makefile:235: compiler] Error 2
``

Here are the versions of software being used:
``
# gcc --version
gcc.exe (Rev10, Built by MSYS2 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# bison --version
bison (GNU Bison) 3.8.2
Written by Robert Corbett and Richard Stallman.

# xxd --version
xxd 2022-01-14 by Juergen Weigert et al.

# flex --version
flex 2.6.4

# g++ --version
g++.exe (Rev10, Built by MSYS2 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``

Thank you for any help you can provide!

**Comment by spotlessmind1975** [comment]
Hello @mrgw454, and **thank you for the bug report!**

The software versions should be fine (I am using Rev6). The problem I think is that the git / operating system you're using to clone/pull the repo doesn't support symlinks. In fact, the error refers to the fact that instead of the file content there is a virtual link to the real file content.

There are two solutions to the problem.

  * The first is to use **git bash 2.39.0.windows.1**, which actually creates the virtual links, and follow the instructions described here: https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201
  * The second is to manually copy the file from the given location (`../d32/_optimizer.c`) to the expected location (`../coco/_optimizer.c`).

The command line to compile the compiler is:

      make target=coco clean compiler

(the `clean` keyword is important)

Let me know if the compilation goes well.

**Comment by spotlessmind1975** [comment]
Hello @mrgw454, first of all thank you very much for letting me know and for describing the workaround. You have been very kind. I will write these instructions into the [installation page](https://retroprogramming.iwashere.eu/ugbasic:installation) as soon as possible.

Since Windows users rarely use the command-line version (and they rarely recompile from source, precisely because it's quite complicated!), I decided that the precompiled hot fixes and cold fixes for Windows are distributed using the most popular and common tool among Windows users, the **[UGBASIC-IDE](https://spotlessmind1975.itch.io/ugbasic-ide)**.

![image](https://user-images.githubusercontent.com/11718606/219108660-93a82ecb-d867-40b9-bc8c-9ed796765094.png)

So whenever in the [Facebook group](https://www.facebook.com/groups/867151224158600) a news of an update is given (as in the case of the `-O bin` option for the `coco` target), it means that the Windows users can download the precompiled compiler with the latest version of the software by simply clicking on the relevant button:

![image](https://user-images.githubusercontent.com/11718606/219109365-c7282eed-9d80-4d10-8d9b-bd85c6a3b449.png)

![image](https://user-images.githubusercontent.com/11718606/219111722-d18a14e1-a153-4778-b9d2-64770bfd8321.png)

Of course, Linux users can recompile it directly from source because it's more practical.

Thank you again for letting me know, and... _happy (retro)coding!_
