### ISSUE TITLE
Adding support for setting a "transparency" color

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#587]
I have imported in a small program an image for the CPC : 
```
BITMAP ENABLE (160,200,16)
CLS
plancheSprite = LOAD IMAGE("explosion_sprites.png")
PUT IMAGE plancheSprite AT 0,0 WITH TRANSPARENCY
WAIT KEY
VAR ink AS WORD
FOR ink = 1 TO 25
	PEN ink
	PRINT "stylo ",  ink
NEXT
WAIT KEY
```
I got the following display on the emulator : 
![image](https://user-images.githubusercontent.com/118670680/230192277-a7575060-3577-4932-b911-d86bff22cced.png)

It seems ok but there's a black pixel that isn't displayed !
As you can see, the black pixel at the right is there, and it is the 15th color : 
![image](https://user-images.githubusercontent.com/118670680/230193013-355df392-c5c6-4357-9bbb-13beaffd3f24.png)

So this is the first problem. 
Then after this image is displayed if I press a key I display each color and I got this : 
![image](https://user-images.githubusercontent.com/118670680/230193627-39f72607-1e4e-4daf-b234-85a50724d911.png)

First : 
Why does the y becomes this big underscore ?
Second : 
On CPC, in this mode I can only have 16 colors at the same time, so I was expecting to have some issues when going above 15, but I don't see the palette displayed in The GIMP, the colors seems to be from a quite random order.
I was hoping to manage the palette only by loading this picture, but it doesn't seem to work, or I still don't understand how the colors work in ugBasic.

Here is the png file : 
![explosion_sprites](https://user-images.githubusercontent.com/118670680/230196918-8d55ef49-4040-42fc-844d-b8923bfdbe9c.png)

Here is the DSK : 
[debug_load_image.cpc.dsk.zip](https://github.com/spotlessmind1975/ugbasic/files/11162653/debug_load_image.cpc.dsk.zip)

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector , first of all, **thank you for the report!** 

This could be an expected behavior. This could be clearer by seeing how ugBASIC interprets colors using the tool made available by UGBASIC-IDE(*)

![image](https://user-images.githubusercontent.com/11718606/230293202-014c04c3-38b7-42ae-85fb-cd67580377c6.png)

As you can see, the palette is all used but the first color (i.e. color 0) is reserved for transparent (that, in turns, is "black"). Which is then used to draw the pixel (and since the TRANSPARENCY keyword is used, the background color is not set). 

So the problem is that there is no correspondence between the background color taken for granted by the algorithm (which is precisely the color black) and the background color of the screen (blue, in this case). 

So it would be necessary to be able to indicate the color (RGB) to be attributed to the transparency, in order to free up another color ink. This should already be available but I need to check if the keyword is still supported by the new algorithm. I'll let you know as soon as possible. As a workaround, you must consider an effective palette of 15 colors when making a `PUT IMAGE` with transparency..

(*) in the next version, at the moment it's still a "work in progress".

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector, for the "y" problem I opened a dedicated issue: #589 .

**Comment by spotlessmind1975** [comment]
Hello @ldir-hector, regarding the order of the colors, you should know that the algorithm that compiles the palette is based on two assumptions. The first is that the same index can be used for the same color. The second is that, once all 15 (3, 1) indexes have been used (the sixteenth, third, second is the background), the indexes can be recycled. Recycling takes place using the first index set at the time. So it's possible that, once the indices run out, the next order might not be the expected one because it will depend on the order in which the new colors are set. 

To avoid this problem, the workaround is to use a known palette for the image and text. Alternatively, if you don't know in advance, use the `COLOR( )` command to obtain the exact color of that index, and thus avoid that the algorithm chooses one of the first ones set.

I hope this helps!

**Comment by ldir-hector** [comment]
Ok, thanks for your detailed answers, I should have noticed that I was already using 16 colors, I guess I should not try to program after 10 PM, I'm getting too old for this ! ;)
There's no hurry for me with the transparency color parameter, I'll use another color instead of black.

Thanks for the COLOR( ) function advice, I now understand that PEN is working as I understood and that COLOR is almost equivalent to the INK instruction of the Amstrad Basic, the differences are that COLOR works with RGB instead of a predefined palette with 27 colors and it has a function aspect to get the current ink at an index wich is quite user friendly !
I put PEN COLOR(ink) in my program and it works quite well !
Thanks, now I can get back to my scorched earth game, since I now clearly understand how theses colors work in ugBasic.

**Comment by ldir-hector** [comment]
I have noticed something weird with PAPER COLOR and PEN COLOR.
On the Amstrad CPC I used to define first the background with the PAPER instruction, then I define the PEN and call CLS to initialize the whole screen with the PAPER color I chose.
On UGBasic, it doesn't work I need to define first the PEN COLOR and only then the PAPER COLOR !

**Comment by spotlessmind1975** [comment]
Added support with the `TRANSPARENCY` and `OPACITY` keywords on `IMAGE LOAD`, `IMAGES LOAD` and `SEQUENCE LOAD`.
