### ISSUE TITLE
"Pen" command doesn't change the foreground color on MSX1 Target as expected

### ISSUE THREAD

**Issue by fmaida** [spotlessmind1975/ugbasic#602]
I'm compiling this short program under ugBASIC 1.13.3 using MSX1 Target:

```basic
init:
	tt = "THE FOX JUMPS OVER THE LAZY DOG"
	color = 2
	
mainloop:
	PEN color
	LOCATE 0, 0
	PRINT tt
	WAIT 100 MS
	DO
		color = color + 1
		IF color > 15 THEN
			color = 2
		ENDIF
		PEN color
		FOR i = 1 TO LEN(tt)
			LOCATE i-1, 0
			PRINT MID(tt, i, 1)
			WAIT 100 MS
		NEXT
	LOOP
```

I was expecting to see the line of text change its color, letter by letter from left to right, and then start over with another color.

Instead I'm experiencing this:

https://user-images.githubusercontent.com/605017/235529245-09475a17-aefd-4af6-853b-d20dc974d631.mp4

Is it a normal behavior or is it a bug?
Thank you in advance

**Comment by spotlessmind1975** [comment]
Hello @fmaida, and **thank you for your bug report!**

Currently, this is not a real "bug" but it is a characteristic behavior of the TMS 9918 chipset, which is the stock video chipset for the `msx1` target. To solve it, it is sufficient to prepend the `BITMAP ENABLE` command, and the expected behavior will be obtained.

```basic

	' Enable a "pixel by pixel" drawing of text

	BITMAP ENABLE

init:
	tt = "THE FOX JUMPS OVER THE LAZY DOG"
	color = 2
	
mainloop:
	PEN color
	LOCATE 0, 0
	PRINT tt
	WAIT 100 MS
	DO
		color = color + 1
		IF color > 15 THEN
			color = 2
		ENDIF
		PEN color
		FOR i = 1 TO LEN(tt)
			LOCATE i-1, 0
			PRINT MID(tt, i, 1)
			WAIT 100 MS
		NEXT
	LOOP
```

The reason you get an "erroneous" behavior is that, in the absence of specific commands for setting the video chip, ugBASIC usually uses the most efficient mode for that target. Usually this is the so-called "text mode" (if present), although sometimes ugBASIC can decide to use a "hybrid" approach, as it does in this case. 

![image](https://user-images.githubusercontent.com/11718606/235543318-12a98ae4-5cb5-41c0-8f63-f4f356d1f950.png)

Indeed, the TMS 9918 chip has a very limited text mode, in terms of colors. To work around the problem, without however slow down everything by using directly the bitmap graphics, it uses a trick and print text by matching a color for each character. So the 'A' character has a specific color, the 'B' character has another color, and so on (P1, P2 and P3 are the very same characters on the above diagram). 

In this way, generally, the problem is solved since the colors are all in all few, and it is guaranteed to represent them on the text, also if used in different section of the screen. Except, sadly, in the case you presented. Indeed, in this case, _each printed character_: should have its own specific color. Having a different color for each character is not enough!

In this case there is no alternative but to turn to bitmap graphics: so printing will no longer take place using the preloaded character set and direct hardware but, instead, the software will draw each individual character, pixel by pixel. By doing so, the above diagram will not be valid but, on the other hand, it will be able to guarantee the color of each single 8x1 pixel line (this is the maximum color resolution of TMS 9918).

I hope the explanation is clear but, if not, then feel free to comment on this same issue.

Thank you again and happy retrocoding!
