### ISSUE TITLE
Impossible to compile DESTINATION keyword

### ISSUE THREAD

**Issue by ldir-hector** [spotlessmind1975/ugbasic#603]
Hello,
I wanted to try BLIT IMAGE with the following code : 

```
Blit image
BITMAP ENABLE(160,200,16)
CLS

COLOR BORDER RGB(0,0,255)
VAR boom AS IMAGE, ciel AS IMAGE, plancheSprite AS IMAGE
VAR back AS IMAGE
plancheSprite = LOAD IMAGE("explosion_sprites.png")
PUT IMAGE plancheSprite AT 0,0 WITH TRANSPARENCY
boom := NEW IMAGE(14,17)
ciel := NEW IMAGE(14,17)
back := NEW IMAGE(158,32)
GET IMAGE boom FROM 1,1
GET IMAGE ciel FROM 15,1
PEN COLOR(11)
BAR 0,100 TO 158,132
GET IMAGE back FROM 0,100
BLIT putimage AS (SOURCE 1)
BLIT puttransmask AS (((DESTINATION) MASKED (INVERSE(TRESHOLD SOURCE 2))) OR (SOURCE 1))
BLIT IMAGE back AT 0,50 WITH putimage
BLIT IMAGE boom,ciel AT 0,0 WITH puttransmask
BLIT IMAGE ciel AT 0,100 WITH putimage
```

But all i got is the following error message at compilation  : syntax error, unexpected T

**Comment by spotlessmind1975** [comment]
Hi @ldir-hector , and **thank you for your bug report!**

I think it's just a typing error. The keyword to use is `THRESHOLD`, with the `H`. By correcting this typo, and removing the first line, which is not a ugBASIC command, the source compiles just fine.

![image](https://user-images.githubusercontent.com/11718606/235729842-7c497776-f928-4ca4-85ce-f0594d6d25ae.png)

The real question is why the IDE highlighted a point that has nothing to do with the error. Unfortunately we have not recompiled the IDE, otherwise I would have entered the instructions in the dictionary and they would have been highlighted, giving you the opportunity to understand what was wrong.

In any case, let me know if you have any other problems.
