### ISSUE TITLE
Compilation error on Mac OS

### ISSUE THREAD

**Issue by dariomode** [spotlessmind1975/ugbasic#613]
Trying to compile under mac os with command

make target=c64 clean compiler

gives the error:

make[1]: *** No rule to make target ../modules/flex/src/../src/*.c', needed by ../modules/flex/src/flex'. Stop.
make: *** [compiler] Error 2

flex version 2.6.4 is currently installed

**Comment by dariomode** [comment]
Trying to compile under mac os with command

make target=c64 clean compiler

gives the error:

make[1]: *** No rule to make target `../modules/flex/src/../src/*.c', needed by `../modules/flex/src/flex'.  Stop.
make: *** [compiler] Error 2

flex version 2.6.4 is currently installed

**Comment by spotlessmind1975** [comment]
Hi @dariomode, and **thank you for the bug report!**

Actually since version 1.13.3, there is no more dependency on a specific version of `flex`, since it has been included in the repository as a submodule. To compile it, you need to issue the following commands:

    git clone https://github.com/spotlessmind1975/ugbasic.git
    cd ugbasic
    git submodule update --recursive --init --remote

Then you can try to compile.

In case you still have problems, try this other command line:

    git submodule update --force --recursive --init --remote

Please, follows this guideline, also:
https://github.com/spotlessmind1975/ugbasic/issues/608#issuecomment-1559801604

Thank you again and have a nice retrocoding!
