### ISSUE TITLE
POKE does not work (z80)

### ISSUE THREAD

**Issue by tquester** [spotlessmind1975/ugbasic#614]
POKE does not work on ZS Spectrum

I want to write a game and since BLIT only works on 8x8 matrix, I decided to write my sprites with PEEK and POKE to the screen.

This code should draw a black line from the top to the bottom of the ZX Spectrum Screen but it does not modify anything.
![poke](https://github.com/spotlessmind1975/ugbasic/assets/5380723/36f5c0c7-36e0-4ad1-8a9c-ac98adf6242c)

Thanks in advance

    BITMAP ENABLE (2)
    DIM base AS INTEGER
    DIM base1 AS INTEGER
    DIM row AS INTEGER
    base = 16384
    FOR a=1 TO 3
        base1 = base
        FOR b = 1 TO 8
            row = base1
            FOR c = 1 TO 8
                POKE row,255
                row = row + 256
            NEXT 
            base1 = base1 + 32
         NEXT 
         base = base + 2048
     NEXT

**Comment by spotlessmind1975** [comment]
Hello @tquester , **thank you for your bug report!**

The bug on `POKE` has been fixed with COLDFIX v1.14 [rev. 20230623.1957].

I currently don't have any limit on the width and height of 8 pixels. It was probably a bug, fixed with the latest release, which I suggest you download and compile. 

This is an example program:

    BITMAP ENABLE (16)
    x := IMAGE LOAD("square8x4.png")
    BLIT xor AS ( SOURCE XOR DESTINATION )
    BLIT IMAGE x AT 0,0 WITH xor

This is the source image:

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/b0044344-4895-4009-bfdb-403010b91b72)

This is the result:

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/e65d58e1-dcb8-4c14-b34b-4c6666497671)
