### ISSUE TITLE
*** ERROR: syntax error, unexpected M, expecting end of file when using MOB in any context (C64)

### ISSUE THREAD

**Issue by Korbaux** [spotlessmind1975/ugbasic#621]
Using the example for MOBs will return this error.

**Comment by spotlessmind1975** [comment]
Hi @Korbaux , and **thank you for your bug report!**

Support for the `MOB` instruction, deprecated since version 1.12, has been removed from version 1.14 ([see release log](https://github.com/spotlessmind1975/ugbasic/releases/tag/v1.14)). Instead, you can use the set of primitives for drawing, acquiring and blitting images. For more information you can refer to these guides and instructions:

  * [Blitting - programming guide](https://retroprogramming.iwashere.eu/ugbasic:user:blit)
  * [`PUT IMAGE`](https://retroprogramming.iwashere.eu/ugbasic:user:kw:put_image) (manual page)
  * [`GET IMAGE`](https://retroprogramming.iwashere.eu/ugbasic:user:kw:get_image) (manual page)
  * `PUT BITMAP`
  * `GET BITMAP`
  * [`BLIT IMAGE`](https://retroprogramming.iwashere.eu/ugbasic:user:kw:blit_image) (manual page)
  * `BLIT BITMAP`

Thank you again, and have a nice retrocoding!
