### ISSUE TITLE
Keystroke undetected under sc3000

### ISSUE THREAD

**Issue by mgovoni** [spotlessmind1975/ugbasic#623]
Hi,

I tried to compile a simple program with IDE. Compilation is ok with no errors, but bluemsx  freeze during execution  after showing "TYPE IN A NUMBER". If I press a number nothing append. I hope it's just a configuration error with MSX.

     PRINT "TYPE IN A NUMBER"
     INPUT a
     PRINT "YOUR NUMBER WAS ";a
     INPUT "WHAT'S YOUR NAME?";name$
     LOCATE 23, : PRINT "HELLO ";name$

Thank you in advance.

**Comment by mgovoni** [comment]
MSX = BLUEMSX Emulator

**Comment by spotlessmind1975** [comment]
Hi @mgovoni, and **thank you for your bug report!**

I confirm that keystrokes are not detected, and indeed the whole keyboard seems not to be present in the emulator. The routine that detects it indicates that the keyboard isn't there, although I'm sure the BlueMSX emulator exposes it. I will do some further analysis and I will update this ticket / the compiler as soon as I fix the bug.

**Comment by spotlessmind1975** [comment]
Hi @mgovoni , thank you again for reporting the bug. The problem has been fixed in the COLDFIX v1.14 [rev. 20230709.1426]. In order to update your compiler is sufficient to download again the compiler for the `sc3000` target using the IDE. If you use Linux instead, simply update your repository and recompile the compiler. 

![image](https://github.com/spotlessmind1975/ugbasic/assets/11718606/6a33a504-e0e4-4ccb-85f7-07d79d4238a3)

**Comment by mgovoni** [comment]
Thank you very much Marco for your wonderful job! I've just tried it and it works!

Max

**Comment by spotlessmind1975** [comment]
Hi @mgovoni, and **thank you for your feedback**!

Allow me to bother to point out that two commands have been added to define speed and delay in keystroke. At the moment, however, there is still no support for the SC-3000 as the latter already has an internal mechanism of this type. However, if necessary, a small refactoring can be thought of to support these commands.
