### ISSUE TITLE
Windows complains after new downloads

### ISSUE THREAD

**Issue by pwillard** [spotlessmind1975/ugbasic#640]
Trojan:Win32/Bearfoos.A!ml
[Detected by Microsoft Defender Antivirus](https://www.microsoft.com/en-us/windows/windows-defender?ocid=cx-wdsi-ency)

UGBC.COCO.EXE updated today.  No issues prior.

**Comment by pwillard** [comment]
I downloaded everything again and it worked but it did cause concern.

**Comment by spotlessmind1975** [comment]
Hello @pwillard , and **thank you for your bug report!**

Since IDE download the ugbc.coco.exe from a safe source (official website), it is a false positive for sure. Using Microsoft Windows it happens, unfortunately. Every executable is compiled "from scratch" from sources, and you could do it by yourself using repository, so really there is no way to add a trojan.

There's not much on my side I can do to prevent that. Most AV tools allow you to submit a false positive once it was verified that no other engine or most other engines do not detect anything. Not sure if you AV has something like that but on my machine, it doesn't flag any of these files. You may check the checksums of the files to verify the file version is the same.
